#!/usr/bin/env bash
TARGET_HOST=$1
[[ -z $TARGET_HOST ]] && echo "!! Host to check wasn't provided" && exit 1
# [[ $(getent hosts ${TARGET_HOST} >/dev/null && echo $?) -ne 0 ]] && echo "!! Hostname/IP not resolvable" && exit 2
while true; do
  check_ping=$(ping -c 1 $TARGET_HOST >& /dev/null; echo $?)
  check_ssh=1
  if [[ $check_ping -eq 0 ]]; then
    msg="\r=== $TARGET_HOST not ready ==="
    check_ssh=$(timeout 1 bash -c "< /dev/tcp/${TARGET_HOST}/22" >& /dev/null; echo $?)
    [[ $check_ssh -eq 0 ]] && msg="\r=== $TARGET_HOST ready to connect ===" 
  else
    msg="\r=== $TARGET_HOST unreachable ==="
  fi
  echo -ne $msg && [[ $check_ssh -eq 0 ]] && echo && break
  sleep 1
done
