#!/usr/bin/env bash

SPANISH=0
SRC=en
DST=es
OUTPUT_FILE=linguee-response.json
while getopts "sq:" PARAM; do
  case $PARAM in
    s)
      SPANISH=1
    ;;
    q)
      QUERY=${OPTARG}
  esac
done

[[ -z $QUERY ]] && echo >&2 '[!!] Query not defined (-q option)' && exit 1
[[ $SPANISH -eq 1 ]] && SRC=$DST && DST=en

REQUEST="\
query=${QUERY// /%20}&\
src=${SRC}&\
dst=${DST}&\
guess_direction:true&\
follow_corrections=on_empty_translations"

curl -s \
-H 'accept: application/json' \
-X GET \
https://linguee-api.fly.dev/api/v2/translations?${REQUEST} \
-o $OUTPUT_FILE 
jp -f $OUTPUT_FILE "[::-1].translations[].{Translate: {Text: text, Examples: examples[]}, Meta: pos}"
rm $OUTPUT_FILE
